import { Navbar, Nav } from "../../styles/header.style";

const NavbarBigComponent = () => {
  return (
    <Navbar.Wrapper>
      <Navbar.Menu>
        <Nav
          activeClass="active"
          to="home"
          spy={true}
          smooth={true}
          offset={-75}
          duration={100}
          role="button"
          tabIndex="0"
          fontWeight={400}
          color={"#6b6b6b"}
        >
          Home
        </Nav>
        <Nav
          to="courses"
          spy={true}
          smooth={true}
          offset={-50}
          duration={100}
          role="button"
          tabIndex="0"
          fontWeight={600}
          color={"#1a1d1f"}
        >
          Courses
        </Nav>
        <Nav
          to="about"
          spy={true}
          smooth={true}
          offset={-60}
          duration={100}
          role="button"
          tabIndex="0"
          fontWeight={400}
          color={"#6b6b6b"}
        >
          Instructor
        </Nav>
        <Nav
          to="faq"
          smooth={true}
          offset={-60}
          duration={100}
          role="button"
          tabIndex="0"
          fontWeight={400}
          color={"#6b6b6b"}
        >
          FAQs
        </Nav>
        <Nav
          to="connect"
          smooth={true}
          duration={100}
          role="button"
          tabIndex="0"
          fontWeight={400}
          color={"#6b6b6b"}
        >
          Connect
        </Nav>
      </Navbar.Menu>
    </Navbar.Wrapper>
  );
};

export default NavbarBigComponent;
